from typing import Any, Optional

from typing_extensions import TypeAlias

_R: TypeAlias = Any
_Optional = Optional
from typing import Optional

import torch
from torch import Tensor

def calculate_gain(
    nonlinearity: Any = ...,
    param: _Optional[int | float] = "```(None)```",
) -> float: ...
def constant(*args, **kwargs) -> ~_R: ...
def constant_(tensor: Tensor = ..., val: float = ...) -> torch.Tensor: ...
def dirac(*args, **kwargs) -> ~_R: ...
def dirac_(tensor: Tensor = ..., groups: int | None = 1) -> torch.Tensor: ...
def eye(*args, **kwargs) -> ~_R: ...
def eye_(tensor: Tensor = ...) -> torch.Tensor: ...
def kaiming_normal(*args, **kwargs) -> ~_R: ...
def kaiming_normal_(
    tensor: Tensor = ...,
    a: float = 0,
    mode: Any = "fan_in",
    nonlinearity: Any = "leaky_relu",
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def kaiming_uniform(*args, **kwargs) -> ~_R: ...
def kaiming_uniform_(
    tensor: Tensor = ...,
    a: float = 0,
    mode: Any = "fan_in",
    nonlinearity: Any = "leaky_relu",
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def normal(*args, **kwargs) -> ~_R: ...
def normal_(
    tensor: Tensor = ...,
    mean: float = 0.0,
    std: float = 1.0,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def ones_(tensor: Tensor = ...) -> torch.Tensor: ...
def orthogonal(*args, **kwargs) -> ~_R: ...
def orthogonal_(
    tensor: Tensor = ...,
    gain: float = 1,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def sparse(*args, **kwargs) -> ~_R: ...
def sparse_(
    tensor: Tensor = ...,
    sparsity: float = ...,
    std: float = 0.01,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def trunc_normal_(
    tensor: Tensor = ...,
    mean: float = 0.0,
    std: float = 1.0,
    a: float = -2.0,
    b: float = 2.0,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def uniform(*args, **kwargs) -> ~_R: ...
def uniform_(
    tensor: Tensor = ...,
    a: float = 0.0,
    b: float = 1.0,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def xavier_normal(*args, **kwargs) -> ~_R: ...
def xavier_normal_(
    tensor: Tensor = ...,
    gain: float = 1.0,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def xavier_uniform(*args, **kwargs) -> ~_R: ...
def xavier_uniform_(
    tensor: Tensor = ...,
    gain: float = 1.0,
    generator: _Optional[torch.Generator] = "```(None)```",
) -> torch.Tensor: ...
def zeros_(tensor: Tensor = ...) -> torch.Tensor: ...
